databases:
  - name: retrofun-db
    plan: free

services:
  - type: web
    name: retro-fun
    env: node
    plan: free
    buildCommand: |
      cd client && npm ci && npm run build
      cd ../server && npm ci
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: retrofun-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
